[project]
name = "qb64-lang-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "pyright>=1.1.406",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-watcher>=0.4.3",
    "ruff>=0.14.1",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.coverage.run]
omit = [
    "*/tests/*",
    "qb64lang/parser/ply.py"
]

[tool.pyright]
include = [
    "qb64lang/*"
]
exclude = [
    "qb64lang/parser/ply.py"
]

[tool.ruff]
include = [
    "qb64lang/*"
]
exclude = [
    "qb64lang/parser/ply.py"
]